### ISSUE TITLE
Glyphs request

### ISSUE THREAD

**Issue by cssobral2013** [indestructible-type/Jones#2]
Add the following glyphs: Sharp S (ß), ae, OE and oe ligatures, [ ], { }, ™, ø, Ø, u with ogonek, Euro sign.

**Comment by EwonRael** [comment]
Hey I know this is kind of a bummer response, but I've stopped developing this font a while back and have kept it here for legacy reasons.

If you are looking for a font with active development and a similar vision, might I suggest looking into the metropolis project https://github.com/chrismsimpson/Metropolis

If this is really urgent or important for some reason I can look into addressing this when I get home.

Hope that's helpful

**Comment by cssobral2013** [comment]
So, if you don't mind I'll fork this for someone that's interested to revive this project.
